apiVersion: apps/v1
kind: Deployment
metadata:
  name: clients-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: clients-service
  template:
    metadata:
      labels:
        app: clients-service
    spec:
      containers:
      - name: clients-service
        image: matthewkaya/cst8915:clients-service-v1 
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: clients-service
spec:
  selector:
    app: clients-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  type: LoadBalancer